services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: creatify
      POSTGRES_USER: creatify
      POSTGRES_PASSWORD: creatify
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py  runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: creatify
      POSTGRES_USER: creatify
      POSTGRES_PASSWORD: creatify
    depends_on:
      - db

volumes:
  postgres_data: